"""This module implements chunking of sequences into smaller segments.

The :code:`ChunkSequence` augmenter is designed to process sequences of features,
dividing  them into smaller chunks according to a specified configuration. This 
augmenter is particularly useful in scenarios where sequences need to be split into 
fixed-size segments for tasks such as time series analysis.

The module includes the following components:

- :code:`ChunkSequenceConfig`: Configuration class defining the chunk size, stride, and 
  whether to keep incomplete chunks.
  features are valid sequences with consistent lengths.
- :code:`ChunkSequenceInputRefs`: Defines the input references required by the augmenter.
- `ChunkSequenceOutputRefs`: Defines the output references generated by the augmenter.
  the chunking configuration.
- :code:`ChunkSequence`: The main class that processes the input sequences and produces 
  chunked output sequences.
"""

from typing import Annotated, Iterable

from datasets.features.features import Features, FeatureType, Sequence
from pydantic import Field
from typing_extensions import Unpack

from hyped.common.feature_checks import (
    get_sequence_feature,
    get_sequence_length,
    raise_feature_is_sequence,
)
from hyped.core.nodes.augmenter import (
    BaseDataAugmenter,
    BaseDataAugmenterConfig,
    Sample,
)
from hyped.core.nodes.base import IOContext
from hyped.core.refs.inputs import FeatureValidator, InputRefs
from hyped.core.refs.outputs import LambdaOutputFeature, OutputRefs
from hyped.core.refs.ref import FeatureRef


class ChunkSequenceConfig(BaseDataAugmenterConfig):
    """Configuration class for the :code:`ChunkSequence` augmenter.

    This class defines the configuration options available for the :code:`ChunkSequence`
    data augmenter, including the size of each chunk, the stride between chunks,
    and whether to keep the last incomplete chunk.
    """

    chunk_size: Annotated[int, Field(ge=1)]
    """The size of each chunk. Must be a positive integer."""

    stride: Annotated[int, Field(ge=1)]
    """The stride between chunks. Defines how far the chunking window moves after
    each chunk. The value must be a positive integer.
    """

    keep_last: bool = True
    """Whether to keep the last incomplete chunk. If True, the last chunk is kept
    even if it does not reach the full chunk size.
    """


def chunk_sequence_feature_validator(
    config: ChunkSequenceConfig, ref: FeatureRef
) -> None:
    """Validate the input feature for chunking.

    This validator ensures that the input feature is a mapping (dictionary) where
    each value is a sequence. It also checks that all sequences have the same length.

    Args:
        config (ChunkSequenceConfig): Configuration object for the ChunkSequence augmenter.
        ref (FeatureRef): Reference to the feature to validate.

    Raises:
        TypeError: If the feature is not a dictionary, if the dictionary is empty,
            or if the sequences have differing lengths.
    """
    # input feature must be a mapping
    if not isinstance(ref.feature_, (Features, dict)):
        raise TypeError(
            "Expected feature `%s` to be of dict type, got %s "
            % (ref.key_, type(ref.feature_))
        )

    # make sure there are any inputs
    if len(ref.feature_) == 0:
        raise TypeError("Feature `%s` cannot be empty." % ref.key_)

    lengths = []

    for key, feature in ref.feature_.items():
        # each value in the mapping needs to be a sequence
        raise_feature_is_sequence(key, feature)
        # keep track of the length of each sequence
        lengths.append(get_sequence_length(feature))

    # find the first length value that is not -1
    target_length = next((x for x in lengths if x != -1), -1)
    # make sure all sequences are of the same length
    if any(length not in {-1, target_length} for length in lengths):
        raise TypeError(
            "All sequences in feature `%s` must have the same length."
            % ref.key_
        )


class ChunkSequenceInputRefs(InputRefs):
    """Input references for the :code:`ChunkSequence` augmenter.

    This class defines the input features required by the :code:`ChunkSequence`
    augmenter, specifically a dictionary of sequences.
    """

    sequences: Annotated[
        FeatureRef, FeatureValidator(chunk_sequence_feature_validator)
    ]
    """A reference to the input sequences. The sequences must be of the same length
    and stored in a dictionary format."""


def build_output_feature(
    config: ChunkSequenceConfig, inputs: ChunkSequenceInputRefs
) -> FeatureType:
    """Build the output feature type for chunked sequences.

    This function determines the structure of the output chunks based on the
    configuration and input sequences. It handles cases where incomplete chunks
    are either kept or discarded.

    Args:
        config (ChunkSequenceConfig): Configuration for the :code:`ChunkSequence` augmenter.
        inputs (ChunkSequenceInputRefs): The input sequences to be chunked.

    Returns:
        FeatureType: The feature type of the chunked output sequences.
    """
    if config.keep_last:
        # get the length of the input sequences
        lengths = map(
            get_sequence_length, inputs["sequences"].feature_.values()
        )
        length = next((x for x in lengths if x != -1), -1)

        # the output sequence length is the chunk size in case
        chunk_sequence_length = (
            -1
            if (length == -1)
            or ((length - config.chunk_size) % config.stride != 0)
            else config.chunk_size
        )

    else:
        # the output chunk size is constant in
        # case in-complete chunks are removed
        chunk_sequence_length = config.chunk_size

    # build the output features
    return Features(
        {
            key: Sequence(
                get_sequence_feature(feature), length=chunk_sequence_length
            )
            for key, feature in inputs["sequences"].feature_.items()
        }
    )


class ChunkSequenceOutputRefs(OutputRefs):
    """Output references for the :code:`ChunkSequence` augmenter.

    This class defines the output features produced by the :code:`ChunkSequence`
    augmenter, specifically the chunks of the input sequences.
    """

    chunks: Annotated[FeatureRef, LambdaOutputFeature(build_output_feature)]
    """The reference to the output chunks of the sequences."""


class ChunkSequence(
    BaseDataAugmenter[
        ChunkSequenceConfig, ChunkSequenceInputRefs, ChunkSequenceOutputRefs
    ]
):
    """The :code:`ChunkSequence` data augmenter.

    This augmenter takes sequences of features as input and divides them into
    smaller chunks based on the provided configuration. The output is a series
    of chunked sequences, which can be used for tasks requiring segmented data.

    The augmenter ensures that all input sequences are of the same length before
    processing, and it handles cases where incomplete chunks can either be kept
    or discarded based on the configuration.
    """

    def process(
        self, inputs: Sample, index: list[int], rank: int, io: IOContext
    ) -> Iterable[Sample]:
        """Process a single input sample and return the corresponding chunks.

        This method divides the input sequences into chunks as specified by the
        configuration. If the :code:`keep_last` flag is set, the last chunk is included
        even if it is smaller than the chunk size.

        Args:
            inputs (Sample): The input sample containing sequences to be chunked.
            index (list[int]): The index associated with the input sample.
            rank (int): The rank of the augmenter in a distributed setting.
            io (IOContext): Context information for the augmenter's execution.

        Returns:
            Iterable[Sample]: The processed output samples, where each sample contains
                a chunk of the input sequences.

        Raises:
            AssertionError: If the input sequences do not have the same length.
        """
        sequences = inputs["sequences"]

        # get the length of the first sequence and make
        # sure all input sequences have the same length
        length = len(next(iter(sequences.values())))
        assert all(
            len(vals) == length for vals in sequences.values()
        ), "All input sequences must have the same length."

        num_chunks = (
            (length // self.config.stride)
            if self.config.keep_last
            else ((length - self.config.chunk_size) // self.config.stride + 1)
        )

        # iterate over all chunks
        for i in range(num_chunks):
            # build the chunk
            yield {
                "chunks": {
                    key: seq[
                        i * self.config.stride : i * self.config.stride
                        + self.config.chunk_size
                    ]
                    for key, seq in sequences.items()
                }
            }

    def call(
        self, **kwargs: Unpack[ChunkSequenceInputRefs]
    ) -> ChunkSequenceOutputRefs:
        """Add the :code:`ChunkSequence` node to the data flow.

        This method processes the input references for the :code:`ChunkSequence` operation,
        adds the corresponding node to the data flow, and returns the references
        to the output chunks generated by the augmenter.

        Args:
            sequences (FeatureRef): The reference to the input sequences to chunk.
            **kwargs (FeatureRef): Additional keyword arguments passed to call method.

        Returns:
            ChunkSequenceOutputRefs: The output references produced by the ChunkSequence augmenter.
        """
        return super(ChunkSequence, self).call(**kwargs)
