"""Module containing processor implementations for sequence operators."""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, TypeVar

from datasets import Sequence  # noqa: F401
from datasets import Value
from typing_extensions import Annotated, Unpack

from hyped.common.feature_checks import (
    check_feature_is_sequence,
    get_sequence_length,
    raise_sequence_lengths_match,
)
from hyped.data.flow.core.nodes.processor import Batch, IOContext
from hyped.data.flow.core.refs.inputs import (
    CheckFeatureEquals,
    CheckFeatureIsSequence,
    GlobalValidator,
)
from hyped.data.flow.core.refs.outputs import LambdaOutputFeature
from hyped.data.flow.core.refs.ref import FeatureRef
from hyped.data.flow.processors.ops.base import (
    BaseBinaryOp,
    BaseBinaryOpConfig,
    BaseBinaryOpOutputRefs,
    BaseUnaryOp,
    BaseUnaryOpConfig,
    BaseUnaryOpOutputRefs,
    BinaryOpInputRefs,
    UnaryOpInputRefs,
)


class BaseUnaryElementWiseOpConfig(BaseUnaryOpConfig):
    """Configuration class for unary element-wise sequence operations."""


class UnaryElementWiseOpInputRefs(UnaryOpInputRefs):
    """Input references for unary element-wise sequence operations."""

    a: Annotated[FeatureRef, CheckFeatureIsSequence(Value)]
    """The input feature. Must be a non-nested sequence type."""


class UnaryElementWiseOpBooleanOutputRefs(BaseUnaryOpOutputRefs):
    """Defines output references for unary element-wise operations with boolean result."""

    result: Annotated[
        FeatureRef,
        LambdaOutputFeature(
            lambda _, i: Sequence(Value("bool"), length=get_sequence_length(i["a"].feature_))
        ),
    ]
    """The boolean result of the operation."""


C = TypeVar("C", bound=BaseUnaryElementWiseOpConfig)
I = TypeVar("I", bound=UnaryElementWiseOpInputRefs)
O_ = TypeVar("O_", bound=BaseUnaryOpOutputRefs)


class BaseUnaryElementWiseOp(BaseUnaryOp[C, I, O_], ABC):
    """Base class for element-wise operations."""

    @abstractmethod
    def op(self, val: Any) -> Any:
        """The element-wise operation to apply."""
        ...

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the element-wise operation.

        Args:
            inputs (Batch): The input batch containing sequence feature 'a'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the element-wise operation.
        """
        return {"result": [[self.op(item) for item in seq] for seq in inputs["a"]]}

    def call(self, **kwargs: Unpack[UnaryElementWiseOpInputRefs]) -> O_:
        """Add the element-wise node to the data flow.

        This method processes the input references for the element-wise operation, adds
        the corresponding node to the data flow, and returns the references to the
        output features generated by the processor.

        Args:
            a (FeatureRef): The input sequence feature for the element-wise operation.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            UnaryElementWiseInputRefs: The output references produced by the
                element-wise operation processor.
        """
        return super(BaseUnaryElementWiseOp, self).call(**kwargs)


class BaseBinaryElementWiseOpConfig(BaseBinaryOpConfig):
    """Configuration class for binary element-wise sequence operations."""


def validate_sequence_inputs(
    config: BaseBinaryElementWiseOpConfig, refs: "BinaryElementWiseOpInputRefs"
) -> None:
    a_key = refs["a"].key_
    b_key = refs["b"].key_

    a_feat = refs["a"].feature_
    b_feat = refs["b"].feature_

    if check_feature_is_sequence(a_feat) and check_feature_is_sequence(b_feat):
        raise_sequence_lengths_match(a_key, b_key, a_feat, b_feat)

    elif not check_feature_is_sequence(a_feat) and not check_feature_is_sequence(b_feat):
        raise TypeError(
            "Both features for element-wise binary operation are of Value type. "
            f"Need min. 1 sequence type. Got {a_key} ({a_feat}) and {b_key} ({b_feat})"
        )


class BinaryElementWiseOpInputRefs(
    Annotated[BinaryOpInputRefs, GlobalValidator(validate_sequence_inputs)]
):
    """Input references for binary element-wise sequence operations."""

    a: Annotated[FeatureRef, CheckFeatureIsSequence(Value) | CheckFeatureEquals(Value)]
    """The first input feature. Must be a value or non-nested sequence type."""

    b: Annotated[FeatureRef, CheckFeatureIsSequence(Value) | CheckFeatureEquals(Value)]
    """The second input feature. Must be a value or non-nested sequence type."""


def infer_output_length(inputs: BinaryElementWiseOpInputRefs) -> int:
    if check_feature_is_sequence(inputs["a"].feature_):
        return get_sequence_length(inputs["a"].feature_)
    elif check_feature_is_sequence(inputs["b"].feature_):
        return get_sequence_length(inputs["b"].feature_)
    else:
        raise RuntimeError("One of `a` or `b` must be of sequence feature type.")


class BinaryElementWiseOpBooleanOutputRefs(BaseBinaryOpOutputRefs):
    """Defines output references for binary element-wise operations with boolean result."""

    result: Annotated[
        FeatureRef,
        LambdaOutputFeature(lambda _, i: Sequence(Value("bool"), length=infer_output_length(i))),
    ]
    """The boolean result of the operation."""


C = TypeVar("C", bound=BaseBinaryElementWiseOpConfig)
I = TypeVar("I", bound=BinaryElementWiseOpInputRefs)
O = TypeVar("O", bound=BaseBinaryOpOutputRefs)


class BaseBinaryElementWiseOp(BaseBinaryOp[C, I, O], ABC):
    """Base class for element-wise operations."""

    @abstractmethod
    def op(self, a: Any, b: Any) -> Any:
        """The binary operation to apply."""

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the element-wise operation.

        Args:
            inputs (Batch): The input batch containing sequence feature 'a'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the element-wise operation.
        """
        # check for broadcasting
        if check_feature_is_sequence(io.inputs["a"]) and check_feature_is_sequence(io.inputs["b"]):
            iterator = (
                [self.op(a, b) for a, b in zip(seq_a, seq_b)]
                for seq_a, seq_b in zip(inputs["a"], inputs["b"])
            )
        elif check_feature_is_sequence(io.inputs["a"]) and not check_feature_is_sequence(
            io.inputs["b"]
        ):
            iterator = (
                [self.op(a, b) for a in seq_a] for seq_a, b in zip(inputs["a"], inputs["b"])
            )
        elif not check_feature_is_sequence(io.inputs["a"]) and check_feature_is_sequence(
            io.inputs["b"]
        ):
            iterator = (
                [self.op(a, b) for b in seq_b] for a, seq_b in zip(inputs["a"], inputs["b"])
            )
        else:
            raise RuntimeError(
                "Element-wise operations only allowed between sequence-sequence "
                f"and sequence-value. Got {io.inputs['a']}-{io.inputs['b']}"
            )

        return {"result": list(iterator)}

    def call(self, **kwargs: Unpack[BinaryElementWiseOpInputRefs]) -> O:
        """Add the element-wise node to the data flow.

        This method processes the input references for the element-wise operation, adds
        the corresponding node to the data flow, and returns the references to the
        output features generated by the processor.

        Args:
            a (FeatureRef): The first input feature.
            b (FeatureRef): The second input feature.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            BaseBinaryOpOutputRefs: The output references produced by the
                element-wise operation processor.
        """
        return super(BaseBinaryElementWiseOp, self).call(**kwargs)
