"""Module containing processor implementations for sequence-query operations.

This module provides data processors for querying sequence features, 
including operations like checking containment, counting occurrences, 
and finding the index of a value within sequences.
"""
from __future__ import annotations

import operator
from abc import ABC, abstractmethod
from typing import Any, TypeVar

from datasets import Value
from typing_extensions import Annotated, Unpack

from hyped.common.feature_checks import check_feature_is_sequence
from hyped.common.typing import Batch, IndexList, Rank
from hyped.core.nodes.processor import (
    BaseDataProcessor,
    BaseDataProcessorConfig,
    IOContext,
)
from hyped.core.refs.inputs import (
    AnyFeatureType,
    CheckFeatureIsSequence,
    GlobalValidator,
    InputRefs,
)
from hyped.core.refs.outputs import OutputFeature, OutputRefs
from hyped.core.refs.ref import FeatureRef


class BaseSequenceQueryOpConfig(BaseDataProcessorConfig):
    """Base Configuration class for sequence-query operations."""


def validate_input_refs(
    config: BaseSequenceQueryOpConfig, refs: SequenceQueryOpInputRefs
) -> None:
    """Post-initialization check to ensure value matches the feature type of the sequence values.

    Args:
        config (BaseSequenceQueryOpConfig): The configuration for the query operation.
        refs (SequenceQueryOpInputRefs): The input references for the query operation.

    Raises:
        TypeError: If the value feature does not match the feature type of the sequence values.
    """
    # make sure the value matches the feature type of the sequence values
    if not check_feature_is_sequence(
        refs["sequence"].feature_, refs["value"].feature_
    ):
        raise TypeError(
            "Value feature type does not match the sequence feature type."
        )


class SequenceQueryOpInputRefs(
    Annotated[InputRefs, GlobalValidator(validate_input_refs)]
):
    """Input references for sequence query operations."""

    sequence: Annotated[FeatureRef, CheckFeatureIsSequence()]
    """The reference to the sequence feature."""

    value: Annotated[FeatureRef, AnyFeatureType()]
    """The reference to the value feature to be checked against the sequence values."""


C = TypeVar("C", bound=BaseSequenceQueryOpConfig)
I = TypeVar("I", bound=SequenceQueryOpInputRefs)
O = TypeVar("O", bound=OutputRefs)


class BaseSequenceQueryOp(BaseDataProcessor[C, I, O], ABC):
    """Base class for sequence query operations.

    This class provides a template for processing operations
    that involve a sequence and a query value.
    """

    @abstractmethod
    def op(self, seq: list[Any], val: Any) -> Any:
        """The sequence-query operation to apply."""

    async def batch_process(
        self, inputs: Batch, index: IndexList, rank: Rank, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the sequence-query operation.

        Args:
            inputs (Batch): The input batch containing features 'a' and 'b'.
            index (IndexList): The indices of the batch.
            rank (Rank): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the sequence-query operation.
        """
        return {
            "result": [
                self.op(a, b)
                for a, b in zip(inputs["sequence"], inputs["value"])
            ]
        }

    def call(self, **kwargs: Unpack[SequenceQueryOpInputRefs]) -> O:
        """Add the sequence-query operation node to the data flow.

        This method processes the input references for the sequence-query operation, adds
        the corresponding node to the data flow, and returns the references to the
        output features generated by the processor.

        Args:
            sequence (FeatureRef): The reference to the sequence feature.
            value (FeatureRef): The reference to the value feature to be checked
                against the sequence values.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            O: The output references produced by the sequence-query data processor.
        """
        return super(BaseSequenceQueryOp, self).call(**kwargs)


class SequenceContainsOutputRefs(OutputRefs):
    """Output references for the :code:`contains` operation."""

    result: Annotated[FeatureRef, OutputFeature(Value("bool"))]
    """The feature reference to the result of the :code:`contains` operation."""


class SequenceContainsConfig(BaseSequenceQueryOpConfig):
    """Configuration class for the :code:`contains` operation."""

    """The :code:`contains` operation."""


class SequenceContains(
    BaseSequenceQueryOp[
        SequenceContainsConfig,
        SequenceQueryOpInputRefs,
        SequenceContainsOutputRefs,
    ]
):
    """Sequence Contains Data Drocessor.

    This class defines the operation that checks if a value is contained within a sequence.
    """

    op = operator.contains


class SequenceCountOfOutputRefs(OutputRefs):
    """Output references for the :code:`countOf` operation."""

    result: Annotated[FeatureRef, OutputFeature(Value("int64"))]
    """The feature reference to the result of the :code:`countOf` operation."""


class SequenceCountOfConfig(BaseSequenceQueryOpConfig):
    """Configuration class for the :code:`countOf operation."""


class SequenceCountOf(
    BaseSequenceQueryOp[
        SequenceCountOfConfig,
        SequenceQueryOpInputRefs,
        SequenceCountOfOutputRefs,
    ]
):
    """:code:`countOf` Data Processor.

    This class defines the operation that counts occurrences of a value within a sequence.
    """

    op = operator.countOf


class SequenceIndexOfOutputRefs(OutputRefs):
    """Output references for the :code:`indexOf` operation."""

    result: Annotated[FeatureRef, OutputFeature(Value("int64"))]
    """The feature reference to the result of the :code:`indexOf` operation."""


class SequenceIndexOfConfig(BaseSequenceQueryOpConfig):
    """Configuration class for the :code:`indexOf` operation."""


class SequenceIndexOf(
    BaseSequenceQueryOp[
        SequenceIndexOfConfig,
        SequenceQueryOpInputRefs,
        SequenceIndexOfOutputRefs,
    ]
):
    """:code:`indexOf` Data Processor.

    This class defines the operation that finds the index of a value within a sequence.
    """

    op = operator.indexOf
