"""Module containing processor implementations for sequence reduction operations.

This module provides data processors for reducing sequence features, 
including operations like computing the length, sum, and mean of sequences.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, TypeVar

from datasets import Value
from typing_extensions import Annotated, Unpack

from hyped.common.feature_checks import SCALAR_TYPES, get_sequence_feature
from hyped.core.nodes.processor import (
    BaseDataProcessor,
    BaseDataProcessorConfig,
    Batch,
    IOContext,
)
from hyped.core.refs.inputs import CheckFeatureIsSequence, InputRefs
from hyped.core.refs.outputs import (
    LambdaOutputFeature,
    OutputFeature,
    OutputRefs,
)
from hyped.core.refs.ref import FeatureRef


class BaseSequenceReduceConfig(BaseDataProcessorConfig):
    """Configuration class for sequence reduction operations."""


class SequenceReduceInputRefs(InputRefs):
    """Input references for sequence reduction operations."""

    a: Annotated[FeatureRef, CheckFeatureIsSequence()]
    """The sequence feature reference for the reduction operation."""


class SequenceReduceScalarInputRefs(SequenceReduceInputRefs):
    """Input references for sequence reduction operations."""

    a: Annotated[FeatureRef, CheckFeatureIsSequence(SCALAR_TYPES)]
    """The sequence feature reference for the reduction operation."""


class BaseSequenceReduceOutputRefs(OutputRefs):
    """Output references for sequence reduction operations."""

    result: Annotated[FeatureRef, OutputFeature(None)]
    """The result of the reduction operation."""


C = TypeVar("C", bound=BaseSequenceReduceConfig)
I = TypeVar("I", bound=SequenceReduceInputRefs)
O = TypeVar("O", bound=BaseSequenceReduceOutputRefs)


class BaseSequenceReduce(BaseDataProcessor[C, I, O], ABC):
    """Base class for sequence reduction operations."""

    @abstractmethod
    def op(self, vals: list) -> Any:
        """The reduction operation to apply."""
        ...

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the reduction operation.

        Args:
            inputs (Batch): The input batch containing sequence feature 'a'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the unary operation.
        """
        return {"result": [self.op(a) for a in inputs["a"]]}

    def call(self, **kwargs: Unpack[SequenceReduceInputRefs]) -> O:
        """Add the UnaryOp node to the data flow.

        This method processes the input references for the BaseSequenceReduce operation, adds
        the corresponding node to the data flow, and returns the references to the
        output features generated by the processor.

        Args:
            a (FeatureRef): The input sequence feature for the reduction operation.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            BaseSequenceReduceOutputRefs: The output references produced by the
                reduction operation processor.
        """
        return super(BaseSequenceReduce, self).call(**kwargs)


class SequenceLengthConfig(BaseSequenceReduceConfig):
    """Configuration class for the Sequence Length operation."""


class SequenceLengthOutputRefs(BaseSequenceReduceOutputRefs):
    """Output references for the Sequence Length operation."""

    result: Annotated[FeatureRef, OutputFeature(Value("int64"))]
    """The feature reference to the length of the sequence."""


class SequenceLength(
    BaseSequenceReduce[
        SequenceLengthConfig,
        SequenceReduceInputRefs,
        SequenceLengthOutputRefs,
    ]
):
    """Sequence Length Data Processor.

    This class defines the operation to get the length of a sequence feature.
    """

    op = len


SCALAR_TYPE_NAMES = [t.dtype for t in SCALAR_TYPES]


def scalar_seq_reduce_infer_dtype(
    inputs: SequenceReduceScalarInputRefs,
    min_precision_type: str = "bool",
) -> Value:
    """Infer the output data type for scalar sequence reduction operations.

    This function determines the appropriate data type for the result of a scalar
    reduction operation on a sequence. It examines the data type of the sequence
    elements and selects a castable scalar type to ensure compatibility with the
    input types.

    Args:
        inputs (SequenceReduceScalarInputRefs): Input references for the sequence
            reduction.
        min_precision_type (str): A minimum precision type to choose. This is useful if
            the output of the operation should be e.g. float, but should still infer the
            precision from the input feature.

    Returns:
        Value: The inferred data type for the result of the sequence reduction operation.
    """
    return Value(
        max(
            get_sequence_feature(inputs["a"].feature_).dtype,
            min_precision_type,
            key=SCALAR_TYPE_NAMES.index,  # this order prefers int over bool
        )
    )


class SequenceSumConfig(BaseSequenceReduceConfig):
    """Configuration class for the Sequence Sum operation."""


class SequenceSumOutputRefs(BaseSequenceReduceOutputRefs):
    """Output references for the Sequence Sum operation."""

    result: Annotated[
        FeatureRef,
        LambdaOutputFeature(
            lambda _, i: scalar_seq_reduce_infer_dtype(i, "int64")
        ),
    ]
    """The feature reference to the sum of the sequence."""


class SequenceSum(
    BaseSequenceReduce[
        SequenceSumConfig,
        SequenceReduceScalarInputRefs,
        SequenceSumOutputRefs,
    ]
):
    """Sequence Sum Data Processor.

    This class defines the operation to get the sum of a sequence feature.
    """

    op = sum


class SequenceMeanConfig(BaseSequenceReduceConfig):
    """Configuration class for the Sequence Mean operation."""


class SequenceMeanOutputRefs(BaseSequenceReduceOutputRefs):
    """Output references for the Sequence Mean operation."""

    result: Annotated[
        FeatureRef,
        LambdaOutputFeature(
            lambda _, i: scalar_seq_reduce_infer_dtype(i, "float32")
        ),
    ]
    """The feature reference to the mean of the sequence."""


class SequenceMean(
    BaseSequenceReduce[
        SequenceMeanConfig,
        SequenceReduceScalarInputRefs,
        SequenceMeanOutputRefs,
    ]
):
    """Sequence Mean Data Processor.

    This class defines the operation to get the mean of a sequence feature.
    """

    def op(self, vals: list) -> Any:
        """The mean operation."""
        return sum(vals) / len(vals)
