"""Provides base classes for nodes in a data flow graph.

This module defines base classes for nodes in a data flow graph. It
includes a base configuration class (:class:`BaseNodeConfig`) and a
generic base class (:class:`BaseNode`) for defining nodes with
configurable input and output types.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Generic, ParamSpec, Protocol, TypeAlias, TypeVar, overload

from hyped._registry.config import BaseConfig, BaseConfigurable
from hyped.common.typing import Index, IndexList, NodeId, Rank

from ..abstract import AbstractDataFlow
from ..typing import Feature
from ..typing.types import BaseTypeFactory as _TypeFactory
from ..typing.types import _Feature

DataFlow: TypeAlias = object


# TODO: legacy code
class IOContext:
    ...


@dataclass(frozen=True)
class RunContext:
    """Context information for the data processors execution.

    Serves as an identifier for the specific call to the processor within the data flow graph.
    This is particularly useful when a single processor class is used multiple times in a data
    flow, as :class:`RunContext` identifies the specific instance of the processor call, i.e.,
    the specific node in the flow graph.
    """

    node_id: NodeId
    """The id of the node in the data flow graph.

    This attribute serves as a unique identifier for the context, ensuring each processor
    call can be distinctly recognized within the flow graph.
    """

    rank: Rank

    index: Index | IndexList

    inputs: dict[str, _Feature]
    """The types of the input features to the node call."""

    output: _TypeFactory
    """The output features expected to be generated by the data processor."""

    def __hash__(self) -> int:
        """Returns a hash value based on the node ID.

        Returns:
            int: The hash value of the node ID.
        """
        return hash(self.node_id)


Params = ParamSpec("Params")
Return = TypeVar("Return", covariant=True)


class CallableProtocol(Protocol, Generic[Params, Return]):
    @overload
    def call(self, *args: Params.args, **kwargs: Params.kwargs) -> Return:
        ...

    @overload
    def call(self, flow: AbstractDataFlow, *args: Params.args, **kwargs: Params.kwargs) -> Return:
        ...

    def call(self, *args: Params.args, **kwargs: Params.kwargs) -> Return:
        ...


class BaseNodeConfig(BaseConfig):
    """Base configuration class for nodes in a data flow graph."""


C = TypeVar("C", bound=BaseNodeConfig)


class BaseNode(BaseConfigurable[C], ABC):
    """Base class for nodes in a data flow graph."""

    @classmethod
    @property
    def Config(self) -> type[C]:
        """Get the configuration type of the node."""
        return self.config_type

    @abstractmethod
    def _call(
        self, flow: None | AbstractDataFlow, args: tuple[Feature], kwargs: dict[str, Feature]
    ) -> _Feature:
        ...

    @overload
    def call(self, *args: Feature, **kwargs: Feature) -> _Feature:
        ...

    @overload
    def call(self, flow: AbstractDataFlow, *args: Feature, **kwargs: Feature) -> _Feature:
        ...

    def call(
        self, *args: AbstractDataFlow | Feature, **kwargs: AbstractDataFlow | Feature
    ) -> _Feature:
        # extract the data flow from the arguments
        flow: None | AbstractDataFlow = (
            None
            if len(args) == 0
            else None
            if not isinstance(args[0], AbstractDataFlow)
            else args[0]
        )

        if flow is not None:
            # remove flow from arguments
            args = args[1:]

        else:
            # try to pop the flow argument form the keyword arguments
            flow = kwargs.pop("flow", None)

        return self._call(flow, args, kwargs)
