"""Module containing processor implementations for sequence random choice operations.

This module provides data processors for operations on sequence features,
including retrieving random items from a sequence.
"""
from __future__ import annotations

from random import choice

from datasets import Sequence, Value  # noqa: F401
from typing_extensions import Annotated, Unpack

from hyped.common.feature_checks import get_sequence_feature  # noqa: F401
from hyped.common.typing import Batch, IndexList, Rank
from hyped.core.nodes.processor import BaseDataProcessor, BaseDataProcessorConfig, IOContext
from hyped.core.refs.inputs import CheckFeatureIsSequence, InputRefs
from hyped.core.refs.outputs import LambdaOutputFeature, OutputRefs
from hyped.core.refs.ref import FeatureRef


class SequenceChoiceInputRefs(InputRefs):
    """Input references for the Random Choice operation."""

    sequence: Annotated[FeatureRef, CheckFeatureIsSequence()]
    """The sequence feature reference from which to randomly choose."""


class SequenceChoiceOutputRefs(OutputRefs):
    """Output references for the Random Choice operation."""

    result: Annotated[
        FeatureRef,
        LambdaOutputFeature(lambda _, i: get_sequence_feature(i["sequence"].feature_)),
    ]
    """The feature reference to the randomly chosen item from the sequence."""


class SequenceChoiceConfig(BaseDataProcessorConfig):
    """Configuration class for the Random Choice operation."""


class SequenceChoice(
    BaseDataProcessor[
        SequenceChoiceConfig,
        SequenceChoiceInputRefs,
        SequenceChoiceOutputRefs,
    ]
):
    """Sequence Random Choice Data Processor.

    This class defines the operation to randomly choose an item from a sequence feature.
    """

    async def batch_process(
        self, inputs: Batch, index: IndexList, rank: Rank, io: IOContext
    ) -> Batch:
        """Process a batch of data for the Random Choice operation.

        Args:
            inputs (Batch): The input batch containing the sequence.
            index (IndexList): The indices of the batch.
            rank (Rank): The rank of the current process.
            io (IOContext): Context information for the data processor's execution.

        Returns:
            Batch: The batch containing the randomly chosen item.
        """
        return {"result": [choice(seq) for seq in inputs["sequence"]]}

    def call(self, **kwargs: Unpack[SequenceChoiceInputRefs]) -> SequenceChoiceOutputRefs:
        """Add the Random Choice node to the data flow.

        This method processes the input references for the Random Choice operation,
        adds the corresponding node to the data flow, and returns the references to
        the output features generated by the processor.

        Args:
            sequence (FeatureRef): The input sequence from which to randomly choose an item.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            SequenceChoiceOutputRefs: The output references produced by the Random Choice data
            processor.
        """
        return super(SequenceChoice, self).call(**kwargs)
