"""Module for testing data augmenter nodes in a data processing pipeline.

This module defines the :class:`BaseDataAugmenterTest` class, which extends
the :class:`BaseNodeTest` class to provide specialized functionality for
testing data :class:`BaseDataAugmenter` nodes.
"""
from typing import ClassVar

from hyped.core.nodes.augmenter import BaseDataAugmenter
from hyped.core.typing import PartitionId

from .base import BaseNodeTest


class BaseDataAugmenterTest(BaseNodeTest):
    """Base class for testing data augmenters.

    This class extends :class:`BaseNodeTest` and provides additional functionality
    for testing data augmenter nodes specifically.

    Subclasses of :class:`BaseDataAugmenterTest` must define the :code:`augmenter`
    class variable, which represents the specific data augmenter (node) to be tested.
    Additionally, they may define the :code:`expected_output_partition` class variable,
    which specifies the expected output partition ID for the augmenter.

    This class provides a testing framework for verifying data augmenters by checking
    both the correctness of the output and the partitioning of the output data.
    """

    augmenter: ClassVar[BaseDataAugmenter]
    """The data augmenter (node) to be tested.

    This class variable must be set by subclasses to specify the augmenter node
    being tested. It should be an instance of `BaseDataAugmenter` or a subclass
    thereof that defines the specific data augmentation logic to be validated in
    the test.
    """

    expected_output_partition: ClassVar[None | PartitionId] = None
    """The expected output partition ID for the augmenter.

    This optional class variable can be set by subclasses to specify the expected
    partition of the output generated by the augmenter. If specified, the test
    will assert that the actual output partition matches this value.
    """

    def execute_test(self) -> None:
        """Executes the test for the data augmenter node.

        This method performs the following steps to test the behavior of the augmenter node:

        1. Calls the augmenter node using the :func:`call_node` method to generate a data
           flow and obtain the output from the node.
        2. Builds the data flow and collects the output into the flow using :func:`flow.build`.
        3. If the :code:`expected_output_partition` is defined, validates that the output
           partition of the augmenter matches the expected partition by checking the
           partition of the output node in the flow's graph.
        4. Executes the flow by passing it to the :func:`execute_flow` method, which processes
           the data and generates output.
        5. Compares the resulting output data against the expected output using the
           :func:`check_output_data_matches_expectation` method.

        This method ensures that the augmenter node behaves as expected, correctly assigns
        partitions to its output (if applicable), and generates output data that matches
        the predefined expectations.
        """
        cls = type(self)
        # call node and build flow
        flow, output = self.call_node(cls.augmenter)
        flow = flow.build(collect={"output": output})
        # check the output partition of the node call
        if cls.expected_output_partition is not None:
            partition = flow._graph.get_node_output_partition(output.ref._node_id)
            assert cls.expected_output_partition == partition, (
                f"Expected output partition {cls.expected_output_partition}, "
                f"but got {partition}."
            )
        # execute the flow and check the output data
        output_data = self.execute_flow(flow)
        cls.check_output_data_matches_expectation(output_data["output"])
