"""Module for testing data augmentor nodes in a data processing pipeline.

This module defines the :class:`BaseDataAugmentorTest` class, which extends
the :class:`BaseNodeTest` class to provide specialized functionality for
testing data :class:`BaseDataAugmentor` nodes.
"""
from typing import Any, ClassVar

from hyped.core.nodes.augmentor import BaseDataAugmentor
from hyped.core.typing import PartitionId
from hyped.typing import Feature

from .base import BaseNodeTest


class BaseDataAugmentorTest(BaseNodeTest):
    """Base class for testing data augmentors.

    This class extends :class:`BaseNodeTest` and provides additional functionality
    for testing data augmentor nodes specifically.

    Subclasses of :class:`BaseDataAugmentorTest` must define the :code:`augmentor`
    class variable, which represents the specific data augmentor (node) to be tested.
    Additionally, they may define the :code:`expected_output_partition` class variable,
    which specifies the expected output partition ID for the augmentor.

    This class provides a testing framework for verifying data augmentors by checking
    both the correctness of the output and the partitioning of the output data.
    """

    augmentor: ClassVar[BaseDataAugmentor]
    """The data augmentor (node) to be tested.

    This class variable must be set by subclasses to specify the augmentor node
    being tested. It should be an instance of `BaseDataAugmentor` or a subclass
    thereof that defines the specific data augmentation logic to be validated in
    the test.
    """

    expected_output_partition: ClassVar[None | PartitionId] = None
    """The expected output partition ID for the augmentor.

    This optional class variable can be set by subclasses to specify the expected
    partition of the output generated by the augmentor. If specified, the test
    will assert that the actual output partition matches this value.
    """

    def execute_test(self) -> tuple[Feature, list[dict[str, Any]]]:
        """Executes the test for the data augmentor node.

        This method performs the following steps to test the behavior of the augmentor node:

        1. Calls the augmentor node using the :func:`call_node` method to generate a data
           flow and obtain the output from the node.
        2. Builds the data flow and collects the output into the flow using :func:`flow.build`.
        3. If the :code:`expected_output_partition` is defined, validates that the output
           partition of the augmentor matches the expected partition by checking the
           partition of the output node in the flow's graph.
        4. Executes the flow by passing it to the :func:`execute_flow` method, which processes
           the data and generates output.
        5. Compares the resulting output data against the expected output using the
           :func:`check_output_data_matches_expectation` method.

        This method ensures that the augmentor node behaves as expected, correctly assigns
        partitions to its output (if applicable), and generates output data that matches
        the predefined expectations.

        Returns:
            tuple[Feature, None | list[dict[str, Any]]]: The output feature that the augmentor
                call returns, as well as the processed data if present. Output data is not present
                when the test doesn't specify any input data.
        """
        cls = type(self)
        # call node and build flow
        flow, output_feature = self.call_node(cls.augmentor)
        flow = flow.build(collect={"output": output_feature})
        # check the output partition of the node call
        if cls.expected_output_partition is not None:
            partition = flow._graph.get_node_output_partition(output_feature.ref._node_id)
            assert cls.expected_output_partition == partition, (
                f"Expected output partition {cls.expected_output_partition}, "
                f"but got {partition}."
            )
        # execute the flow and check the output data
        if (output_arrow := self.execute_flow(flow)) is not None:
            output_data = output_arrow["output"].to_pylist()
            type(self).check_output_data_matches_expectation(output_data)
            return output_feature, output_data
        else:
            # return only the output feature and None for the output data
            return output_feature, None
