"""
Progress Monitor Module

This module provides the :class:`ProgressMonitor` class, which is designed to track data
processing tasks. It serves as a centralized mechanism to monitor the state and progression
of workers.
"""

import math
import multiprocessing as mp
import threading
from enum import Enum
from time import time
from typing import Iterable, TypedDict

from hyped.common.typing import Rank
from hyped.common.utils import TimeWeightedEMA

from .runners.base import WorkerRole


class TimeReport(TypedDict):
    """
    Reports the time spent by a worker in different stages.
    """

    producer: float
    """The time taken for the producer stage in seconds."""

    processor: float
    """The time taken for the processor stage in seconds."""

    finalizer: float
    """The time taken for the finalizer stage in seconds."""


class ProgressReport(TypedDict):
    """
    Represents a progress report detailing worker's timing and sample information.
    """

    timestamp: float
    """The timestamp when the report was generated."""

    elapsed_time: float
    """The time elapsed since the last report, in seconds."""

    num_samples: int
    """The number of samples processed since the last report."""

    average_time: TimeReport
    """The average time spent by the worker in each role (producer, processor, finalizer)."""

    total_time: TimeReport
    """The total time spent by the worker in each role (producer, processor, finalizer)."""


class ShardState(Enum):
    """Enum representing the processing state of a dataset shard."""

    PENDING = 1
    """
    Indicates that the shard is pending and has not yet been assigned to a worker.
    """

    IN_PROGRESS = 2
    """
    Indicates that the shard is currently being processed by a worker.
    """

    COMPLETED = 3
    """
    Indicates that the shard has been fully processed by a worker.
    """

    CANCELED = 4
    """
    Indicates that the processing of the shard has been canceled before completion.
    """


class ProgressMonitor(object):
    """Monitors the state and progress of all workers.

    The :class:`ProgressMonitor` tracks the state of each shard, the role and status of each
    worker, and the number of samples processed, providing utilities for reporting progress and
    checking worker and shard statuses.
    """

    def __init__(self, num_shards: int, num_workers: int, queue: mp.Queue, item_size: int) -> None:
        """Initializes the :class:`ProgressMonitor`.

        Args:
            num_shards (int): The total number of shards to process.
            num_workers (int): The number of workers processing the data.
            queue (mp.Queue): Sample queue filled by producer in stage 2.
            item_size (int): The number of samples contained within a queue item.
        """

        self._stopping = threading.Event()
        self._done = threading.Event()
        # track buffer queue
        self._queue = queue
        self._item_size = item_size
        # track shards
        self._num_shards = num_shards
        self._shard_state = [ShardState.PENDING] * num_shards
        # track workers
        self._num_workers = num_workers
        self._alive = [False] * num_workers
        self._roles = [None] * num_workers
        self._shard = [None] * num_workers

        decay_rate = math.log(2) / 1  # 1s half-life time
        # track samples generated by each worker in different roles
        self._time_ema = [
            {
                "producer": TimeWeightedEMA(decay_rate),
                "processor": TimeWeightedEMA(decay_rate),
                "finalizer": TimeWeightedEMA(decay_rate),
            }
            for _ in range(num_workers)
        ]
        self._num_samples = [
            {
                WorkerRole.PROCESSOR: 0,
                WorkerRole.PRODUCER: 0,
                WorkerRole.CONSUMER: 0,
            }
            for _ in range(num_workers)
        ]

    def get_worker_role(self, rank: Rank) -> None | WorkerRole:
        """Returns the current role of a worker.

        Args:
            rank (Rank): The worker's rank.

        Returns:
            WorkerRole | None: The role of the worker or None if the worker has no assigned role.
        """
        return self._roles[rank]

    @property
    def num_processed_samples(self) -> int:
        """Returns the total number of samples processed by all workers.

        The count includes samples processed by both processors and consumers.
        It excludes the samples processed by producers as these samples are not
        finalized yet and would be counted twice, once by the producer and and
        once by the consumer.

        Returns:
            int: The total number of processed samples.
        """
        return sum(
            nums[WorkerRole.PROCESSOR] + nums[WorkerRole.CONSUMER] for nums in self._num_samples
        )

    def _report_progress(self, rank: Rank, report: ProgressReport) -> None:
        """Capture the progress report of a worker.

        Args:
            rank (Rank): The rank of the worker reporting progress.
            report (dict): A dictionary containing the worker's report data, including
                timestamps, average processing times, and the number of samples processed.
        """
        ts = report["timestamp"]
        # save worker report
        self._time_ema[rank]["producer"].update(ts, report["average_time"]["producer"])
        self._time_ema[rank]["processor"].update(ts, report["average_time"]["processor"])
        self._time_ema[rank]["finalizer"].update(ts, report["average_time"]["finalizer"])
        # update processed samples
        role = self._roles[rank]
        self._num_samples[rank][role] += report["num_samples"]

    def avg_times(self, ranks: None | Iterable[Rank] = None) -> dict[str, float]:
        """Returns the average processing times for each worker task.

        Recall that the process workflow of each worker has three stages, namely:

        - :code:`producer`: produce the sample to be processed
        - :code:`processor`: process the sample
        - :code:`finalizer`: finalize the sample

        These are not to be confused with the worker roles.

        Args:
            ranks (Iterable[Rank] | None): Optional list of worker ranks to calculate
                average times for. If None, all workers are included.

        Returns:
            dict[str, float]: A dictionary mapping worker processing stages to their
            respective average times.
        """
        # sort ranks by timestamp
        ranks = ranks if ranks is not None else range(self.num_workers)
        ranks = [r for r in ranks if self._time_ema[r]["producer"].timestamp is not None]
        ranks = sorted(ranks, key=lambda r: self._time_ema[r]["producer"].timestamp)

        times = {}
        for key in ["producer", "processor", "finalizer"]:
            global_ema = TimeWeightedEMA(decay_rate=math.log(2) / 1)

            for rank in ranks:
                local_ema = self._time_ema[rank][key]
                global_ema.update(local_ema.timestamp, local_ema.value)

            if len(ranks) > 0:
                now = time()
                local_ema = self._time_ema[ranks[0]][key]
                global_ema.update(now, now - local_ema.timestamp)

            times[key] = global_ema.value

        return times

    @property
    def num_shards(self) -> int:
        """Returns the total number of dataset shards to process.

        Returns:
            int: The total number of shards.
        """
        return self._num_shards

    @property
    def num_workers(self) -> int:
        """Returns the total number of workers.

        Returns:
            int: The total number of workers.
        """
        return self._num_workers

    @property
    def num_buffered_samples(self) -> int:
        """Returns the number of samples currently buffered in the queue awaiting processing.

        This property calculates the total number of samples that are waiting in the queue by
        multiplying the number of items in the queue by the item size (the number of samples
        contained in each item).

        Returns:
            int: The total number of samples currently buffered in the queue.
        """
        try:
            return self._queue.qsize() * self._item_size
        except (BrokenPipeError, ConnectionResetError):
            # queue connection closed
            return 0

    def _mark_as_stopping(self) -> None:
        """Marks the process as stopping."""
        self._stopping.set()

    def _mark_as_done(self) -> None:
        """Marks the process as done."""
        self._done.set()

    @property
    def is_stopping(self) -> bool:
        """Checks if the process is in a stopping state.

        Returns:
            bool: True if the process is stopping, False otherwise.
        """
        return self._stopping.is_set()

    def get_worker_shard(self, rank: Rank) -> None | int:
        """Retrieves the shard currently assigned to the worker.

        Args:
            rank (Rank): The rank of the worker whose assigned shard is to be retrieved.

        Returns:
            None | int: The shard ID assigned to the worker, or None if no shard is currently
            assigned to the worker.
        """

        return self._shard[rank]

    def _mark_shard_in_progress(self, rank: Rank, shard_id: int) -> None:
        """Marks a shard as being in progress, associating it with a worker.

        Args:
            rank (Rank): The rank of the worker processing the shard.
            shard_id (int): The identifier of the shard being processed.
        """
        self._shard_state[shard_id] = ShardState.IN_PROGRESS
        self._shard[rank] = shard_id

    def _mark_shard_completed(self, shard_id: int) -> None:
        """Marks a shard as completed once processing is finished.

        Args:
            shard_id (int): The identifier of the shard that is completed.
        """
        self._shard_state[shard_id] = ShardState.COMPLETED

    def _mark_shard_canceled(self, shard_id: int) -> None:
        """Marks a shard as canceled.

        Args:
            shard_id (int): The identifier of the shard that is canceled.
        """
        self._shard_state[shard_id] = ShardState.CANCELED

    @property
    def any_pending_shards(self) -> bool:
        """Checks if there are any pending shards.

        Returns:
            bool: True if there are shards pending, False otherwise.
        """
        return ShardState.PENDING in set(self._shard_state)

    @property
    def pending_shards(self) -> set[int]:
        """Returns a set of shard IDs that are pending.

        Returns:
            set[int]: A set of shard IDs in the :code:`PENDING` state.
        """
        return {i for i, state in enumerate(self._shard_state) if state is ShardState.PENDING}

    @property
    def completed_shards(self) -> set[int]:
        """Returns a set of shard IDs that have been completed.

        Returns:
            set[int]: A set of shard IDs in the :code:`COMPLETED` state.
        """
        return {i for i, state in enumerate(self._shard_state) if state is ShardState.COMPLETED}

    def _mark_worker_ready(self, rank: Rank) -> None:
        """Marks a worker as ready to process tasks.

        Args:
            rank (Rank): The rank of the worker being marked as ready.
        """
        self._alive[rank] = True

    def _mark_worker_done(self, rank: Rank) -> None:
        """Marks a worker as done and no longer processing.

        Args:
            rank (Rank): The rank of the worker being marked as done.
        """
        assert self._roles[rank] is None
        self._alive[rank] = False

    def _mark_worker_idling(self, rank: Rank) -> None:
        """Marks a worker as idle, with no current role.

        Args:
            rank (Rank): The rank of the worker being marked as idle.
        """
        assert self._alive[rank]
        self._roles[rank] = None

    def _mark_worker_busy(self, rank: Rank, role: WorkerRole) -> None:
        """Marks a worker as busy with a specific role.

        Args:
            rank (Rank): The rank of the worker being marked as busy.
            role (WorkerRole): The role that the worker is performing.
        """
        assert self._alive[rank]
        self._roles[rank] = role

    def _mark_worker_completed(self, rank: Rank) -> None:
        """Marks a worker's current task as completed.

        Also marks the corresponding shard as completed.

        Args:
            rank (Rank): The rank of the worker who has completed.
        """
        shard_id = self._shard[rank]
        if shard_id is not None:
            self._mark_shard_completed(shard_id)
            self._shard[rank] = None

    def _mark_worker_canceled(self, rank: Rank) -> None:
        """Marks a worker's current task as completed.

        Also marks the corresponding shard as canceled.

        Args:
            rank (Rank): The rank of the worker who has canceled their task.
        """
        shard_id = self._shard[rank]
        if shard_id is not None:
            self._mark_shard_canceled(shard_id)
            self._shard[rank] = None

    @property
    def any_worker_alive(self) -> bool:
        """Checks if any workers are currently alive.

        Returns:
            bool: True if any workers are alive, False otherwise.
        """
        return any(self._alive)

    @property
    def alive_workers(self) -> set[Rank]:
        """Returns a set of ranks of all workers that are currently alive.

        Returns:
            set[Rank]: A set of worker ranks that are alive.
        """
        return {i for i, alive in enumerate(self._alive) if alive}

    @property
    def idle_workers(self) -> set[Rank]:
        """Returns a set of ranks of workers that are currently idle.

        Returns:
            set[Rank]: A set of worker ranks that are idle (i.e., have no assigned role).
        """
        return {i for i, role in enumerate(self._roles) if role is None}

    @property
    def busy_workers(self) -> set[Rank]:
        """Returns a set of ranks of workers that are currently busy.

        Returns:
            set[Rank]: A set of worker ranks that are busy.
        """
        return {i for i, role in enumerate(self._roles) if role is not None}

    def get_workers_with_role(self, role: WorkerRole) -> set[Rank]:
        """Returns a set of ranks of workers assigned a specific role.

        Args:
            role (WorkerRole): The role to filter workers by.

        Returns:
            set[Rank]: A set of worker ranks that are assigned the specified role.
        """
        return {i for i, r in enumerate(self._roles) if r is role}
