import orjson
from typing_extensions import Unpack

from hyped.common.typing import Batch, Index, IndexList, Rank, Sample

from .base import BaseParser, IOContext, ParserException
from .json import JsonParserConfig, JsonParserInputRefs, JsonParserOutputRefs


class FastJsonParserConfig(JsonParserConfig):
    ...


class FastJsonParser(BaseParser[FastJsonParserConfig, JsonParserInputRefs, JsonParserOutputRefs]):
    async def batch_process(
        self, inputs: Batch, index: IndexList, rank: Rank, io: IOContext
    ) -> Batch:
        """Parse a batch of JSON strings.

        This method attempts to parse a batch of JSON strings as a single operation,
        improving performance. If a json parser error occurs, it falls back to parsing
        each sample individually and identifies which samples raised errors.

        Args:
            inputs (Batch): The batch of input samples containing JSON strings to process.
            index (IndexList): The indices associated with the input samples.
            rank (Rank): The rank of the processor in a distributed setting.
            io (IOContext): Context information for the data processor's execution.

        Returns:
            Batch: A batch containing the parsed objects or a list of exceptions for
            individual samples that failed validation.
        """

        batch_json_string = (
            (b'{"parsed_batch": [%b]}' % b",".join(inputs["payload"]))
            if io.inputs["payload"].dtype == "binary"
            else ('{"parsed_batch": [%s]}' % ",".join(inputs["payload"]))
        )

        try:
            # try to load the batch in one operation
            parsed_batch = orjson.loads(batch_json_string)
            return Batch(obj=parsed_batch["parsed_batch"], exception=[None] * len(index))
        except orjson.JSONDecodeError:
            # fallback to processing each sample individually and identify the
            # samples that raise the validation error
            return await super().batch_process(inputs, index, rank, io)

    async def parse(self, inputs: Sample, index: Index, rank: Rank, io: IOContext) -> Sample:
        """Parse a single JSON-string to a dictionary object.

        This method parses a JSON string contained within the input sample and validates it
        against a predefined model. If the configuration is set to catch validation errors,
        it will handle any validation exceptions and return a default model with an error message.
        Otherwise, it will directly parse and validate the JSON string.

        Args:
            inputs (Sample): The input sample containing the JSON string to be processed.
            index (Index): The index associated with the input sample.
            rank (Rank): The rank of the processor in a distributed setting.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Sample: The parsed object.

        Raises:
            ParserException: If validation of the JSON string fails and
                :code:`config.catch_validation_errors` is False.
        """

        json_string = (
            (b'{"parsed": %b}' % inputs["payload"])
            if io.inputs["payload"].dtype == "binary"
            else ('{"parsed": %s}' % inputs["payload"])
        )

        try:
            # try to parse the json string
            parsed_sample = orjson.loads(json_string)
            return parsed_sample["parsed"]
        except orjson.JSONDecodeError as e:
            # raise a parser exception from the validation error
            raise ParserException(str(e)) from e

    def call(self, **kwargs: Unpack[JsonParserInputRefs]) -> JsonParserOutputRefs:
        """Add the JsonParser node to the data flow.

        This method processes the input references for the JsonParser operation, adds
        the corresponding node to the data flow, and returns the references to the
        output features generated by the processor.

        Args:
            json_str (FeatureRef): The reference to the json string to parse.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            JsonParserOutputRefs: The output references produced by the JsonParser processor.
        """
        return super(FastJsonParser, self).call(**kwargs)
