from abc import ABC, abstractmethod
from typing import Annotated, Any, TypeVar

from datasets import Value
from typing_extensions import Unpack

from hyped.data.flow.core.nodes.base import IOContext
from hyped.data.flow.core.nodes.processor import BaseDataProcessor, BaseDataProcessorConfig, Batch
from hyped.data.flow.core.refs.inputs import AnyFeatureType, InputRefs
from hyped.data.flow.core.refs.outputs import OutputFeature, OutputRefs
from hyped.data.flow.core.refs.ref import FeatureRef


class BooleanOutputRefs(OutputRefs):
    """Defines output references for operations with boolean result."""

    result: Annotated[FeatureRef, OutputFeature(Value("bool"))]
    """The result of the operation."""


class BaseUnaryOpConfig(BaseDataProcessorConfig, ABC):
    """Configuration class for unary operations."""


class UnaryOpInputRefs(InputRefs):
    """Defines input references for unary operations."""

    a: Annotated[FeatureRef, AnyFeatureType()]
    """The input feature. Can be any type."""


class BaseUnaryOpOutputRefs(OutputRefs):
    """Defines output references for unary operations."""

    result: Annotated[FeatureRef, OutputFeature(None)]
    """The result of the numeric unary operation. Placeholder type."""


C = TypeVar("C", bound=BaseUnaryOpConfig)
I = TypeVar("I", bound=UnaryOpInputRefs)
O = TypeVar("O", bound=BaseUnaryOpOutputRefs)


class BaseUnaryOp(BaseDataProcessor[C, I, O], ABC):
    """Base class for unary operations."""

    @abstractmethod
    def op(self, val: Any) -> Any:
        """The unary operation to apply."""
        ...

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the unary operation.

        Args:
            inputs (Batch): The input batch containing feature 'a'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the unary operation.
        """
        return {"result": [self.op(a) for a in inputs["a"]]}

    def call(self, **kwargs: Unpack[UnaryOpInputRefs]) -> O:
        """Add the UnaryOp node to the data flow.

        This method processes the input references for the BaseUnaryOp operation, adds
        the corresponding node to the data flow, and returns the references to the
        output features generated by the processor.

        Args:
            a (FeatureRef): The input feature for the unary operation.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            BaseUnaryOpOutputRefs: The output references produced by the unary operation processor.
        """
        return super(BaseUnaryOp, self).call(**kwargs)


class BaseBinaryOpConfig(BaseDataProcessorConfig):
    """Configuration class for binary operations."""


class BinaryOpInputRefs(InputRefs):
    """Defines input references for binary operations."""

    a: Annotated[FeatureRef, AnyFeatureType()]
    """The first input feature. Can be any type."""

    b: Annotated[FeatureRef, AnyFeatureType()]
    """The second input feature. Can be any type."""


class BaseBinaryOpOutputRefs(OutputRefs, ABC):
    """Defines output references for binary operations."""

    result: Annotated[FeatureRef, OutputFeature(None)]
    """The result of the binary operation. Placeholder type."""


C = TypeVar("C", bound=BaseBinaryOpConfig)
I = TypeVar("I", bound=BinaryOpInputRefs)
O = TypeVar("O", bound=BaseBinaryOpOutputRefs)


class BaseBinaryOp(BaseDataProcessor[C, I, O], ABC):
    """Base class for binary operations."""

    @abstractmethod
    def op(self, a: Any, b: Any) -> Any:
        """The binary operation to apply."""

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the binary operation.

        Args:
            inputs (Batch): The input batch containing features 'a' and 'b'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the binary operation.
        """
        return {"result": [self.op(a, b) for a, b in zip(inputs["a"], inputs["b"])]}

    def call(self, **kwargs: Unpack[BinaryOpInputRefs]) -> O:
        """Add the binary operation node to the data flow.

        This method processes the input references for the binary operation, adds
        the corresponding node to the data flow, and returns references to the output features
        generated by the processor.

        Args:
            a (FeatureRef): The first input feature.
            b (FeatureRef): The second input feature.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            O: The output references produced by the binary operation processor.
        """
        return super(BaseBinaryOp, self).call(**kwargs)
