import operator
from abc import ABC, abstractmethod
from typing import Annotated, Any, TypeVar

from datasets import Value
from typing_extensions import Unpack

from hyped.data.flow.core.nodes.processor import BaseDataProcessor, Batch, IOContext
from hyped.data.flow.core.refs.inputs import CheckFeatureEquals
from hyped.data.flow.core.refs.outputs import OutputFeature
from hyped.data.flow.core.refs.ref import FeatureRef
from hyped.data.flow.processors.ops.base import (
    BaseBinaryOpConfig,
    BaseBinaryOpOutputRefs,
    BinaryOpInputRefs,
    BooleanOutputRefs,
)


class BaseBinaryValueOpConfig(BaseBinaryOpConfig):
    """Configuration class for binary operations."""


class BinaryValueOpInputRefs(BinaryOpInputRefs):
    """Defines input references for binary operations."""

    a: Annotated[FeatureRef, CheckFeatureEquals(Value)]
    """The first input feature. Must be a Value type."""

    b: Annotated[FeatureRef, CheckFeatureEquals(Value)]
    """The second input feature. Must be a Value type."""


class BaseBinaryValueOpOutputRefs(BaseBinaryOpOutputRefs, ABC):
    """Defines output references for binary operations."""

    result: Annotated[FeatureRef, OutputFeature(None)]
    """The result of the binary operation. Placeholder type."""


C = TypeVar("C", bound=BaseBinaryValueOpConfig)
I = TypeVar("I", bound=BinaryValueOpInputRefs)
O = TypeVar("O", bound=BaseBinaryValueOpOutputRefs)


class BaseBinaryValueOp(BaseDataProcessor[C, I, O], ABC):
    """Base class for binary value operations."""

    @abstractmethod
    def op(self, a: Any, b: Any) -> Any:
        """The binary operation to apply."""

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the binary operation.

        Args:
            inputs (Batch): The input batch containing features 'a' and 'b'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the binary operation.
        """
        return {"result": [self.op(a, b) for a, b in zip(inputs["a"], inputs["b"])]}

    def call(self, **kwargs: Unpack[BinaryValueOpInputRefs]) -> O:
        """Add the binary operation node to the data flow.

        This method processes the input references for the binary operation, adds
        the corresponding node to the data flow, and returns references to the output features
        generated by the processor.

        Args:
            a (FeatureRef): The first input feature.
            b (FeatureRef): The second input feature.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            O: The output references produced by the binary operation processor.
        """
        return super().call(**kwargs)


class BaseValueComparatorConfig(BaseBinaryValueOpConfig):
    """Configuration class for standard comparator operations."""


C = TypeVar("C", bound=BaseValueComparatorConfig)


class BaseValueComparator(BaseBinaryValueOp[C, BinaryValueOpInputRefs, BooleanOutputRefs]):
    """Base class for value comparator operations.

    Comparators are characterized by their ability to take inputs of value type
    and output a boolean feature.
    """

    @abstractmethod
    def op(self, a: Any, b: Any) -> bool:
        """The comparator operation to be applied.

        Takes inputs and outputs a boolean feature.
        """


class EqualsConfig(BaseValueComparatorConfig):
    """Configuration class for the equality operation."""


class Equals(BaseValueComparator[EqualsConfig]):
    """Processor for the equality operation."""

    op = operator.eq


class NotEqualsConfig(BaseValueComparatorConfig):
    """Configuration class for the inequality operation."""


class NotEquals(BaseValueComparator[NotEqualsConfig]):
    """Processor for the inequality operation."""

    op = operator.ne
