import operator
from abc import ABC, abstractmethod
from typing import Annotated, Any, TypeVar

from datasets import Value
from typing_extensions import Unpack

from hyped.data.flow.core.nodes.processor import BaseDataProcessor, Batch, IOContext
from hyped.data.flow.core.refs.inputs import CheckFeatureEquals
from hyped.data.flow.core.refs.ref import FeatureRef
from hyped.data.flow.processors.ops.base import (
    BaseBinaryOpConfig,
    BaseUnaryOpConfig,
    BinaryOpInputRefs,
    BooleanOutputRefs,
    UnaryOpInputRefs,
)


class BaseUnaryBooleanOpConfig(BaseUnaryOpConfig):
    """Configuration class for unary operations."""


class UnaryBooleanOpInputRefs(UnaryOpInputRefs):
    """Defines input references for unary operations."""

    a: Annotated[FeatureRef, CheckFeatureEquals(Value("bool"))]
    """The input feature. Must be boolean type."""


C = TypeVar("C", bound=BaseUnaryBooleanOpConfig)
I = TypeVar("I", bound=UnaryBooleanOpInputRefs)
O = TypeVar("O", bound=BooleanOutputRefs)


class BaseUnaryBooleanOp(BaseDataProcessor[C, I, O], ABC):
    """Base class for boolean unary operations."""

    @abstractmethod
    def op(self, val: bool) -> bool:
        """The unary operation to apply."""
        ...

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the unary operation.

        Args:
            inputs (Batch): The input batch containing feature 'a'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the unary operation.
        """
        return {"result": [self.op(a) for a in inputs["a"]]}

    def call(self, **kwargs: Unpack[UnaryBooleanOpInputRefs]) -> O:
        """Add the BaseBooleanUnaryOp node to the data flow.

        This method processes the input references for the BaseBooleanUnaryOp operation, adds
        the corresponding node to the data flow, and returns the references to the
        output features generated by the processor.

        Args:
            a (FeatureRef): The input feature for the unary operation.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            BooleanOutputRefs: The output references produced by the unary operation processor.
        """
        return super(BaseUnaryBooleanOp, self).call(**kwargs)


class BooleanInvertConfig(BaseUnaryBooleanOpConfig):
    """Configuration class for the negation operation."""


class BooleanInvert(
    BaseUnaryBooleanOp[BooleanInvertConfig, UnaryBooleanOpInputRefs, BooleanOutputRefs]
):
    """Processor for the negation operation."""

    # operator.invert is not the same as boolean negation
    def op(self, b):
        return not b


class BaseBinaryBooleanOpConfig(BaseBinaryOpConfig):
    """Configuration class for boolean binary operations."""


class BinaryBooleanOpInputRefs(BinaryOpInputRefs):
    """Defines input references for boolean binary operations."""

    a: Annotated[FeatureRef, CheckFeatureEquals(Value("bool"))]
    """The first input feature. Must be of boolean type."""

    b: Annotated[FeatureRef, CheckFeatureEquals(Value("bool"))]
    """The second input feature. Must be of boolean type."""


C = TypeVar("C", bound=BaseBinaryBooleanOpConfig)
I = TypeVar("I", bound=BinaryBooleanOpInputRefs)
O = TypeVar("O", bound=BooleanOutputRefs)


class BaseBinaryBooleanOp(BaseDataProcessor[C, I, O], ABC):
    """Base class for boolean binary operations."""

    @abstractmethod
    def op(self, a: bool, b: bool) -> Any:
        """The binary operation to apply."""

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the binary operation.

        Args:
            inputs (Batch): The input batch containing features 'a' and 'b'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the binary operation.
        """
        return {"result": [self.op(a, b) for a, b in zip(inputs["a"], inputs["b"])]}

    def call(self, **kwargs: Unpack[BinaryBooleanOpInputRefs]) -> O:
        """Add the boolean binary operation node to the data flow.

        This method processes the input references for the binary operation, adds
        the corresponding node to the data flow, and returns references to the output features
        generated by the processor.

        Args:
            a (FeatureRef): The first input feature.
            b (FeatureRef): The second input feature.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            O: The output references produced by the binary operation processor.
        """
        return super().call(**kwargs)


class BaseLogicalOpConfig(BaseBinaryBooleanOpConfig):
    """Configuration class for logical operations."""


C = TypeVar("C", bound=BaseLogicalOpConfig)


class BaseLogicalOp(BaseBinaryBooleanOp[C, BinaryBooleanOpInputRefs, BooleanOutputRefs]):
    """Base class for logical operations."""


class LogicalAndConfig(BaseLogicalOpConfig):
    """Configuration class for the logical AND operation."""


class LogicalAnd(BaseLogicalOp[LogicalAndConfig]):
    """Processor for the logical AND operation."""

    op = operator.and_


class LogicalOrConfig(BaseLogicalOpConfig):
    """Configuration class for the logical OR operation."""


class LogicalOr(BaseLogicalOp[LogicalOrConfig]):
    """Processor for the logical OR operation."""

    op = operator.or_


class LogicalXOrConfig(BaseLogicalOpConfig):
    """Configuration class for the logical XOR operation."""


class LogicalXOr(BaseLogicalOp[LogicalXOrConfig]):
    """Processor for the logical XOR operation."""

    op = operator.xor
