import operator
from abc import ABC, abstractmethod
from typing import Annotated, Any, TypeVar

from datasets import Value
from typing_extensions import Unpack

from hyped.common.feature_checks import INT_TYPES, NUMERIC_TYPES
from hyped.data.flow.core.nodes.processor import BaseDataProcessor, Batch, IOContext
from hyped.data.flow.core.refs.inputs import CheckFeatureEquals
from hyped.data.flow.core.refs.outputs import LambdaOutputFeature, OutputFeature
from hyped.data.flow.core.refs.ref import FeatureRef
from hyped.data.flow.processors.ops.base import (
    BaseBinaryOpConfig,
    BaseBinaryOpOutputRefs,
    BaseUnaryOpConfig,
    BaseUnaryOpOutputRefs,
    BinaryOpInputRefs,
    BooleanOutputRefs,
    UnaryOpInputRefs,
)


class BaseUnaryNumericOpConfig(BaseUnaryOpConfig):
    """Configuration class for unary operations."""


class UnaryNumericOpInputRefs(UnaryOpInputRefs):
    """Defines input references for unary operations."""

    a: Annotated[FeatureRef, CheckFeatureEquals(NUMERIC_TYPES)]
    """The input feature. Must be a numeric type."""


class UnaryNumericOpOutputRefs(BaseUnaryOpOutputRefs):
    """Defines output references for numeric unary operations."""

    result: Annotated[
        FeatureRef,
        LambdaOutputFeature(lambda config, inputs: inputs["a"].feature_),
    ]
    """The result of the numeric unary operation."""


C = TypeVar("C", bound=BaseUnaryNumericOpConfig)
I = TypeVar("I", bound=UnaryNumericOpInputRefs)
O = TypeVar("O", bound=UnaryNumericOpOutputRefs)


class BaseUnaryNumericOp(BaseDataProcessor[C, I, O], ABC):
    """Base class for unary operations."""

    @abstractmethod
    def op(self, val: float | int) -> float | int:
        """The unary operation to apply."""
        ...

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the unary operation.

        Args:
            inputs (Batch): The input batch containing feature 'a'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the unary operation.
        """
        return {"result": [self.op(a) for a in inputs["a"]]}

    def call(self, **kwargs: Unpack[UnaryNumericOpInputRefs]) -> O:
        """Add the UnaryOp node to the data flow.

        This method processes the input references for the UnaryOp operation, adds
        the corresponding node to the data flow, and returns the references to the
        output features generated by the processor.

        Args:
            a (FeatureRef): The input feature for the unary operation.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            BaseUnaryOpOutputRefs: The output references produced by the unary operation processor.
        """
        return super(BaseUnaryNumericOp, self).call(**kwargs)


class NegConfig(BaseUnaryNumericOpConfig):
    """Configuration class for the negation operation."""


class Neg(BaseUnaryNumericOp[NegConfig, UnaryNumericOpInputRefs, UnaryNumericOpOutputRefs]):
    """Processor for the negation operation."""

    op = operator.neg


class AbsConfig(BaseUnaryNumericOpConfig):
    """Configuration class for the absolute operation."""


class Abs(BaseUnaryNumericOp[AbsConfig, UnaryNumericOpInputRefs, UnaryNumericOpOutputRefs]):
    """Processor for the absolute operation."""

    op = operator.abs


class InvertConfig(BaseUnaryNumericOpConfig):
    """Configuration class for the bitwise inversion operation."""


class InvertInputRefs(UnaryNumericOpInputRefs):
    """Defines input references for NumericInvert operations."""

    a: Annotated[FeatureRef, CheckFeatureEquals(INT_TYPES)]
    """The input feature. Must be a integer type."""


class Invert(BaseUnaryNumericOp[InvertConfig, InvertInputRefs, UnaryNumericOpOutputRefs]):
    """Processor for the bitwise inversion operation."""

    op = operator.invert


class BaseBinaryNumericOpConfig(BaseBinaryOpConfig):
    """Configuration class for binary operations."""


class BinaryNumericOpInputRefs(BinaryOpInputRefs):
    """Defines input references for binary operations."""

    a: Annotated[FeatureRef, CheckFeatureEquals(NUMERIC_TYPES)]
    """The first input feature. Must be a numerical type."""

    b: Annotated[FeatureRef, CheckFeatureEquals(NUMERIC_TYPES)]
    """The second input feature. Must be a numerical type."""


class BaseBinaryNumericOpOutputRefs(BaseBinaryOpOutputRefs, ABC):
    """Defines output references for binary operations."""


C = TypeVar("C", bound=BaseBinaryNumericOpConfig)
I = TypeVar("I", bound=BinaryNumericOpInputRefs)
O = TypeVar("O", bound=BaseBinaryNumericOpOutputRefs)


class BaseBinaryNumericOp(BaseDataProcessor[C, I, O], ABC):
    """Base class for binary operations."""

    @abstractmethod
    def op(self, a: float | int, b: float | int) -> Any:
        """The binary operation to apply."""

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the binary operation.

        Args:
            inputs (Batch): The input batch containing features 'a' and 'b'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the binary operation.
        """
        return {"result": [self.op(a, b) for a, b in zip(inputs["a"], inputs["b"])]}

    def call(self, **kwargs: Unpack[BinaryNumericOpInputRefs]) -> O:
        """Add the binary operation node to the data flow.

        This method processes the input references for the binary operation, adds
        the corresponding node to the data flow, and returns references to the output features
        generated by the processor.

        Args:
            a (FeatureRef): The first input feature.
            b (FeatureRef): The second input feature.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            O: The output references produced by the binary operation processor.
        """
        return super().call(**kwargs)


class BaseNumericComparatorConfig(BaseBinaryNumericOpConfig):
    """Configuration class for numeric comparator operations."""


C = TypeVar("C", bound=BaseNumericComparatorConfig)


class BaseNumericComparator(BaseBinaryNumericOp[C, BinaryNumericOpInputRefs, BooleanOutputRefs]):
    """Base class for numeric comparator operations.

    Comparators are characterized by their ability to take inputs of numeric value type
    and output a boolean feature.
    """

    @abstractmethod
    def op(self, a: float | int, b: float | int) -> bool:
        """The comparator operation to be applied.

        Takes numeric inputs and outputs a boolean feature.
        """


class LessThanConfig(BaseNumericComparatorConfig):
    """Configuration class for the less-than operation."""


class LessThan(BaseNumericComparator[LessThanConfig]):
    """Processor for the less-than operation."""

    op = operator.lt


class LessThanOrEqualConfig(BaseNumericComparatorConfig):
    """Configuration class for the less-than-or-equal operation."""


class LessThanOrEqual(BaseNumericComparator[LessThanOrEqualConfig]):
    """Processor for the less-than-or-equal operation."""

    op = operator.le


class GreaterThanConfig(BaseNumericComparatorConfig):
    """Configuration class for the greater-than operation."""


class GreaterThan(BaseNumericComparator[GreaterThanConfig]):
    """Processor for the greater-than operation."""

    op = operator.gt


class GreaterThanOrEqualConfig(BaseNumericComparatorConfig):
    """Configuration class for the greater-than-or-equal operation."""


class GreaterThanOrEqual(BaseNumericComparator[GreaterThanOrEqualConfig]):
    """Processor for the greater-than-or-equal operation."""

    op = operator.ge


class BaseClosedOpConfig(BaseBinaryNumericOpConfig):
    """Configuration class for closed mathematical operations."""


NUMERICAL_TYPE_NAMES = [t.dtype for t in NUMERIC_TYPES]


def closed_op_infer_dtype(config: BaseClosedOpConfig, inputs: BinaryNumericOpInputRefs) -> Value:
    """Infers the output data type for closed operations based on input types.

    For closed operations, the inferred output data type is determined by the input data types.
    If both inputs are integers, the output data type will be an integer. If both inputs are floats,
    the output data type will be a float. For a mixture of integers and floats, the output data
    type will be float.

    Args:
        config (ClosedOpConfig): The configuration for the closed operation.
        inputs (MathInputRefs): The input references.

    Returns:
        Value: The inferred data type for the output.
    """
    return Value(
        max(
            inputs["a"].feature_.dtype,
            inputs["b"].feature_.dtype,
            key=NUMERICAL_TYPE_NAMES.index,  # this order prefers higher precision types
        )
    )


class ClosedOpOutputRefs(BaseBinaryNumericOpOutputRefs):
    """Defines output references for closed mathematical operations."""

    result: Annotated[FeatureRef, LambdaOutputFeature(closed_op_infer_dtype)]
    """The result of the closed mathematical operation."""


C = TypeVar("C", bound=BaseClosedOpConfig)


class BaseClosedOp(BaseBinaryNumericOp[C, BinaryNumericOpInputRefs, ClosedOpOutputRefs]):
    """Base class for closed mathematical operations.

    Closed operations are characterized by preserving closure within the set of
    values they operate on. Such operators include addition or subtraction, but
    not division, as division may result in values outside the set of integers or
    floats when dividing certain numbers. For example, while adding two integers
    always results in another integer, dividing one integer by another may produce
    a non-integer result.
    """

    @abstractmethod
    def op(self, a: int | float, b: int | float) -> int | float:
        """The closed mathematical operation to be applied.

        Closed mathematical operations are operations where applying the operation to two operands
        always results in a value within the same data type domain as the operands, preserving
        closure within the set of values.
        """


class AddConfig(BaseClosedOpConfig):
    """Configuration class for the addition operation."""


class Add(BaseClosedOp[AddConfig]):
    """Processor for the addition operation."""

    op = operator.add


class SubConfig(BaseClosedOpConfig):
    """Configuration class for the subtraction operation."""


class Sub(BaseClosedOp[SubConfig]):
    """Processor for the subtraction operation."""

    op = operator.sub


class MulConfig(BaseClosedOpConfig):
    """Configuration class for the multiplication operation."""


class Mul(BaseClosedOp[MulConfig]):
    """Processor for the multiplication operation."""

    op = operator.mul


class PowConfig(BaseClosedOpConfig):
    """Configuration class for the power operation."""


class Pow(BaseClosedOp[PowConfig]):
    """Processor for the power operation."""

    op = operator.pow


class ModConfig(BaseClosedOpConfig):
    """Configuration class for the modulus operation."""


class Mod(BaseClosedOp[ModConfig]):
    """Processor for the modulus operation."""

    op = operator.mod


class FloorDivConfig(BaseBinaryNumericOpConfig):
    """Configuration class for the floor division operation."""


class FloorDivOutputRefs(BaseBinaryNumericOpOutputRefs):
    """Defines output references for the floor division operation."""

    result: Annotated[FeatureRef, OutputFeature(Value("int32"))]
    """The result of the floor division operation."""


class FloorDiv(BaseBinaryNumericOp[FloorDivConfig, BinaryNumericOpInputRefs, FloorDivOutputRefs]):
    """Processor for the floor division operation."""

    op = operator.floordiv


class TrueDivConfig(BaseBinaryNumericOpConfig):
    """Configuration class for the true division operation."""


class TrueDivOutputRefs(BaseBinaryNumericOpOutputRefs):
    """Defines output references for the true division operation."""

    result: Annotated[FeatureRef, OutputFeature(Value("float32"))]
    """The result of the true division operation."""


class TrueDiv(BaseBinaryNumericOp[TrueDivConfig, BinaryNumericOpInputRefs, TrueDivOutputRefs]):
    """Processor for the true division operation."""

    op = operator.truediv
