"""Module containing processor implementations for sequence operators."""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, TypeVar

from datasets import Value
from typing_extensions import Annotated, Unpack

from hyped.common.feature_checks import SCALAR_TYPES
from hyped.data.flow.core.nodes.processor import Batch, IOContext
from hyped.data.flow.core.refs.inputs import CheckFeatureIsSequence
from hyped.data.flow.core.refs.outputs import LambdaOutputFeature, OutputFeature
from hyped.data.flow.core.refs.ref import FeatureRef
from hyped.data.flow.processors.ops.base import (
    BaseUnaryOp,
    BaseUnaryOpConfig,
    BaseUnaryOpOutputRefs,
    UnaryOpInputRefs,
)


class BaseSequenceAggregateConfig(BaseUnaryOpConfig):
    """Configuration class for sequence aggregation operations."""


class SequenceAggregationInputRefs(UnaryOpInputRefs):
    """Input references for sequence aggregation operations."""

    a: Annotated[FeatureRef, CheckFeatureIsSequence()]
    """The sequence feature reference for the aggregation operation."""


class SequenceAggregationScalarInputRefs(UnaryOpInputRefs):
    """Input references for sequence aggregation operations."""

    a: Annotated[FeatureRef, CheckFeatureIsSequence(SCALAR_TYPES)]
    """The sequence feature reference for the aggregation operation."""


class BaseSequenceAggregationOutputRefs(BaseUnaryOpOutputRefs):
    """Output references for sequence aggreagtion operations."""


C = TypeVar("C", bound=BaseSequenceAggregateConfig)
I = TypeVar("I", bound=SequenceAggregationInputRefs)
O = TypeVar("O", bound=BaseSequenceAggregationOutputRefs)


class BaseSequenceAggregation(BaseUnaryOp[C, I, O], ABC):
    """Base class for sequence aggregation operations."""

    @abstractmethod
    def op(self, vals: list) -> Any:
        """The aggregation operation to apply."""
        ...

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the aggregation operation.

        Args:
            inputs (Batch): The input batch containing sequence feature 'a'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the unary operation.
        """
        return {"result": [self.op(a) for a in inputs["a"]]}

    def call(self, **kwargs: Unpack[SequenceAggregationInputRefs]) -> O:
        """Add the UnaryOp node to the data flow.

        This method processes the input references for the BaseSequenceAggregation operation, adds
        the corresponding node to the data flow, and returns the references to the
        output features generated by the processor.

        Args:
            a (FeatureRef): The input sequence feature for the aggregation operation.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            BaseSequenceAggregationOutputRefs: The output references produced by the
                aggregation operation processor.
        """
        return super(BaseSequenceAggregation, self).call(**kwargs)


class SequenceLengthConfig(BaseSequenceAggregateConfig):
    """Configuration class for the Sequence Length operation."""


class SequenceLengthOutputRefs(BaseSequenceAggregationOutputRefs):
    """Output references for the Sequence Length operation."""

    result: Annotated[FeatureRef, OutputFeature(Value("int64"))]
    """The feature reference to the length of the sequence."""


class SequenceLength(
    BaseSequenceAggregation[
        SequenceLengthConfig,
        SequenceAggregationInputRefs,
        SequenceLengthOutputRefs,
    ]
):
    """Sequence Length Data Processor.

    This class defines the operation to get the length of a sequence feature.
    """

    op = len


SCALAR_TYPE_NAMES = [t.dtype for t in SCALAR_TYPES]


def scalar_seq_aggr_infer_dtype(
    config: BaseSequenceAggregateConfig, inputs: SequenceAggregationScalarInputRefs
) -> Value:
    return Value(
        max(
            inputs["a"].feature_.feature.dtype,
            "int32",
            key=SCALAR_TYPE_NAMES.index,  # this order prefers int over bool
        )
    )


class SequenceSumConfig(BaseSequenceAggregateConfig):
    """Configuration class for the Sequence Sum operation."""


class SequenceSumOutputRefs(BaseSequenceAggregationOutputRefs):
    """Output references for the Sequence Sum operation."""

    result: Annotated[FeatureRef, LambdaOutputFeature(scalar_seq_aggr_infer_dtype)]
    """The feature reference to the sum of the sequence."""


class SequenceSum(
    BaseSequenceAggregation[
        SequenceSumConfig,
        SequenceAggregationScalarInputRefs,
        SequenceSumOutputRefs,
    ]
):
    """Sequence Sum Data Processor.

    This class defines the operation to get the sum of a sequence feature.
    """

    op = sum


class SequenceMeanConfig(BaseSequenceAggregateConfig):
    """Configuration class for the Sequence Mean operation."""


class SequenceMeanOutputRefs(BaseSequenceAggregationOutputRefs):
    """Output references for the Sequence Mean operation."""

    result: Annotated[FeatureRef, LambdaOutputFeature(scalar_seq_aggr_infer_dtype)]
    """The feature reference to the mean of the sequence."""


class SequenceMean(
    BaseSequenceAggregation[
        SequenceMeanConfig,
        SequenceAggregationScalarInputRefs,
        SequenceMeanOutputRefs,
    ]
):
    """Sequence Mean Data Processor.

    This class defines the operation to get the mean of a sequence feature.
    """

    def op(self, vals: list) -> Any:
        """The mean operation."""
        return sum(vals) / len(vals)
