"""Module containing processor implementations for sequence item operators."""
from __future__ import annotations

from collections import deque
from functools import partial
from itertools import starmap

import numpy as np
from datasets import Sequence  # noqa: F401
from typing_extensions import Annotated, Unpack

from hyped.common.feature_checks import (
    INDEX_TYPES,
    check_feature_equals,
    check_feature_is_sequence,
    get_sequence_feature,
    get_sequence_length,
)
from hyped.data.flow.core.nodes.processor import (
    BaseDataProcessor,
    BaseDataProcessorConfig,
    Batch,
    IOContext,
)
from hyped.data.flow.core.refs.inputs import (
    AnyFeatureType,
    CheckFeatureEquals,
    CheckFeatureIsSequence,
    GlobalValidator,
    InputRefs,
)
from hyped.data.flow.core.refs.outputs import LambdaOutputFeature, OutputRefs
from hyped.data.flow.core.refs.ref import FeatureRef


class SequenceGetItemInputRefs(InputRefs):
    """Input references for the GetItem operation."""

    sequence: Annotated[FeatureRef, CheckFeatureIsSequence()]
    """The sequence feature reference."""

    # either an index or a sequence of indices
    index: Annotated[
        FeatureRef,
        CheckFeatureEquals(INDEX_TYPES) | CheckFeatureIsSequence(INDEX_TYPES),
    ]
    """The index or sequence of indices to get items from the sequence."""


class SequenceGetItemOutputRefs(OutputRefs):
    """Output references for the GetItem operation."""

    gathered: Annotated[
        FeatureRef,
        LambdaOutputFeature(
            lambda _, i: (
                Sequence(
                    feature=get_sequence_feature(i["sequence"].feature_),
                    length=get_sequence_length(i["index"].feature_),
                )
                if check_feature_is_sequence(i["index"].feature_)
                else get_sequence_feature(i["sequence"].feature_)
            )
        ),
    ]
    """The feature reference to the gathered items from the sequence."""


class SequenceGetItemConfig(BaseDataProcessorConfig):
    """Configuration class for the GetItem operation."""


class SequenceGetItem(
    BaseDataProcessor[
        SequenceGetItemConfig,
        SequenceGetItemInputRefs,
        SequenceGetItemOutputRefs,
    ]
):
    """Sequence GetItem Data Processor.

    This class defines the operation to get items from a sequence feature based
    on the given index or indices.
    """

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Process a batch of data for the GetItem operation.

        Args:
            inputs (Batch): The input batch containing features 'a' and 'b'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the binary operation.
        """
        op = (
            (lambda s, idx: list(map(s.__getitem__, idx)))
            if check_feature_is_sequence(io.inputs["index"])
            else (lambda s, i: s[i])
        )

        return {
            "gathered": list(
                starmap(op, zip(inputs["sequence"], inputs["index"]))
            )
        }

    def call(
        self, **kwargs: Unpack[SequenceGetItemInputRefs]
    ) -> SequenceGetItemOutputRefs:
        """Add the GetItem node to the data flow.

        This method processes the input references for the GetItem operation, adds
        the corresponding node to the data flow, and returns the references to the
        output features generated by the processor.

        Args:
            sequence (FeatureRef): The input sequence from which to extract an item.
            index (FeatureRef): The index at which to extract the item from the sequence.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            SequenceGetItemOutputRefs: The output references produced by the GetItem data processor.
        """
        return super(SequenceGetItem, self).call(**kwargs)


def validate_setitem_input_refs(
    config: SequenceSetItemConfig, refs: SequenceSetItemInputRefs
) -> None:
    """Ensure values align for setting in the sequence.

    Args:
        config (SequenceSetItemConfig): The configuration for the setitem operation.
        refs (SequenceSetItemInputRefs): The input references for the setitem operation.

    Raises:
        TypeError: If the values do not match the required type or length.
    """
    if check_feature_is_sequence(refs["index"].feature_):
        # make sure the values match the other inputs, i.e.
        #  - values must be a sequence
        #  - values sequence must have the same length as the index
        #  - values must be of the same type as the values in the sequence
        # TODO: support broadcasting of values, i.e. values can be a single value
        #       even if the index is a sequence of indices, np.put implements the
        #       broadcasting logic anyways
        if (
            (not check_feature_is_sequence(refs["value"].feature_))
            or (
                (get_sequence_length(refs["value"].feature_) != -1)
                and (get_sequence_length(refs["index"].feature_) != -1)
                and (
                    get_sequence_length(refs["value"].feature_)
                    != get_sequence_length(refs["index"].feature_)
                )
            )
            or (
                not check_feature_equals(
                    get_sequence_feature(refs["value"].feature_),
                    get_sequence_feature(refs["sequence"].feature_),
                )
            )
        ):
            raise TypeError("Values must match the sequence type and length.")

    else:
        # values must be a single value of the correct type
        if not check_feature_equals(
            refs["value"].feature_,
            get_sequence_feature(refs["sequence"].feature_),
        ):
            raise TypeError("Value must match the sequence type.")


class SequenceSetItemInputRefs(
    Annotated[InputRefs, GlobalValidator(validate_setitem_input_refs)]
):
    """Input references for the SetItem operation."""

    sequence: Annotated[FeatureRef, CheckFeatureIsSequence()]
    """The sequence feature reference."""

    # either an index or a sequence of indices
    index: Annotated[
        FeatureRef,
        CheckFeatureEquals(INDEX_TYPES) | CheckFeatureIsSequence(INDEX_TYPES),
    ]
    """The index or sequence of indices to set items in the sequence."""

    value: Annotated[FeatureRef, AnyFeatureType()]
    """The value or sequence of values to set at the specified indices in the sequence."""


class SequenceSetItemOutputRefs(OutputRefs):
    """Output references for the SetItem operation."""

    result: Annotated[
        FeatureRef, LambdaOutputFeature(lambda _, i: i["sequence"].feature_)
    ]
    """The feature reference to the result of the SetItem operation."""


class SequenceSetItemConfig(BaseDataProcessorConfig):
    """Configuration class for the SetItem operation."""

    ignore_length_mismatch: bool = False
    """Whether to ignore length mismatch between index and value sequences."""


class SequenceSetItem(
    BaseDataProcessor[
        SequenceSetItemConfig,
        SequenceSetItemInputRefs,
        SequenceSetItemOutputRefs,
    ]
):
    """Sequence SetItem Data Processor.

    This class defines the operation to set items in a sequence feature based
    on the given index or indices.
    """

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Process a batch of data for the SetItem operation.

        Args:
            inputs (Batch): The input batch containing features 'a' and 'b'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the binary operation.
        """
        (
            (lambda s, idx: list(map(s.__getitem__, idx)))
            if check_feature_is_sequence(io.inputs["index"])
            else (lambda s, i: s[i])
        )

        if (
            not self.config.ignore_length_mismatch
            and check_feature_is_sequence(io.inputs["index"])
            and (
                (get_sequence_length(io.inputs["index"]) == -1)
                or (get_sequence_length(io.inputs["value"]) == -1)
            )
        ):
            # make sure the length of the value and index list match
            if any(
                len(vals) != len(idx)
                for vals, idx in zip(inputs["value"], inputs["index"])
            ):
                raise RuntimeError()  # TODO: write error message

        # convert sequences to numpy arrays and create all put operations
        sequences = list(
            map(partial(np.asarray, dtype=object), inputs["sequence"])
        )
        operations = starmap(
            np.put, zip(sequences, inputs["index"], inputs["value"])
        )
        # efficiently exhaust operations iterator, basically run all operations
        deque(operations, maxlen=0)

        # convert arrays with new values back to python lists
        return {"result": list(map(np.ndarray.tolist, sequences))}

    def call(
        self, **kwargs: Unpack[SequenceSetItemInputRefs]
    ) -> SequenceSetItemOutputRefs:
        """Add the SetItem node to the data flow.

        This method processes the input references for the SetItem operation, adds
        the corresponding node to the data flow, and returns the references to the
        output features generated by the processor.

        Args:
            sequence (FeatureRef): The input sequence in which items will be set.
            index (FeatureRef): The index or indices at which to set the items in the sequence.
            value (FeatureRef): The value or values to set at the specified indices in the sequence.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            SequenceSetItemOutputRefs: The output references produced by the SetItem data processor.
        """
        return super(SequenceSetItem, self).call(**kwargs)
