"""Module containing processor implementations for sequence operators."""
from __future__ import annotations

import operator
from abc import ABC, abstractmethod
from typing import Any, ClassVar, TypeVar

from datasets import Value
from typing_extensions import Annotated, Unpack

from hyped.common.feature_checks import check_feature_is_sequence
from hyped.data.flow.core.nodes.processor import (
    BaseDataProcessor,
    BaseDataProcessorConfig,
    Batch,
    IOContext,
)
from hyped.data.flow.core.refs.inputs import (
    AnyFeatureType,
    CheckFeatureIsSequence,
    GlobalValidator,
    InputRefs,
)
from hyped.data.flow.core.refs.outputs import OutputFeature, OutputRefs
from hyped.data.flow.core.refs.ref import FeatureRef


def validate_seqvalop_input_refs(
    config: BaseSequenceValueOpConfig, refs: SequenceValueOpInputRefs
) -> None:
    """Post-initialization check to ensure value matches the feature type of the sequence values.

    Args:
        config (BaseSequenceValueOpConfig): The configuration for the valop operation.
        refs (SequenceValueOpInputRefs): The input references for the valop operation.

    Raises:
        TypeError: If the value feature does not match the feature type of the sequence values.
    """
    # make sure the value matches the feature type of the sequence values
    if not check_feature_is_sequence(
        refs["sequence"].feature_, refs["value"].feature_
    ):
        raise TypeError(
            "Value feature type does not match the sequence feature type."
        )


class SequenceValueOpInputRefs(
    Annotated[InputRefs, GlobalValidator(validate_seqvalop_input_refs)]
):
    """Input references for sequence value operations."""

    sequence: Annotated[FeatureRef, CheckFeatureIsSequence()]
    """The reference to the sequence feature."""

    value: Annotated[FeatureRef, AnyFeatureType()]
    """The reference to the value feature to be checked against the sequence values."""


class BaseSequenceValueOpConfig(BaseDataProcessorConfig):
    """Base Configuration class for sequence-value operations."""


C = TypeVar("C", bound=BaseSequenceValueOpConfig)
I = TypeVar("I", bound=SequenceValueOpInputRefs)
O = TypeVar("O", bound=OutputRefs)


class BaseSequenceValueOp(BaseDataProcessor[C, I, O], ABC):
    """Base class for sequence value operations.

    This class provides a template for processing operations that involve a sequence and a value.

    Attributes:
        _OUTPUT_KEY (str): The key for the output feature in the result batch.
    """

    _OUTPUT_KEY: ClassVar[str]

    @abstractmethod
    def op(self, seq: list[Any], val: Any) -> Any:
        """The sequence-value operation to apply."""

    async def batch_process(
        self, inputs: Batch, index: list[int], rank: int, io: IOContext
    ) -> Batch:
        """Processes a batch of inputs, applying the sequence-value operation.

        Args:
            inputs (Batch): The input batch containing features 'a' and 'b'.
            index (list[int]): The indices of the batch.
            rank (int): The rank of the current process.
            io (IOContext): Context information for the data processors execution.

        Returns:
            Batch: The batch containing the result of the sequence-value operation.
        """
        return {
            type(self)._OUTPUT_KEY: [
                self.op(a, b)
                for a, b in zip(inputs["sequence"], inputs["value"])
            ]
        }

    def call(self, **kwargs: Unpack[SequenceValueOpInputRefs]) -> O:
        """Add the sequence-value operation node to the data flow.

        This method processes the input references for the sequence-value operation, adds
        the corresponding node to the data flow, and returns the references to the
        output features generated by the processor.

        Args:
            sequence (FeatureRef): The reference to the sequence feature.
            value (FeatureRef): The reference to the value feature to be checked
                against the sequence values.
            **kwargs (FeatureRef): Keyword arguments passed to call method.

        Returns:
            O: The output references produced by the sequence-value data processor.
        """
        return super(BaseSequenceValueOp, self).call(**kwargs)


class SequenceContainsOutputRefs(OutputRefs):
    """Output references for the :code:`contains` operation."""

    contains: Annotated[FeatureRef, OutputFeature(Value("bool"))]
    """The feature reference to the result of the :code:`contains` operation."""


class SequenceContainsConfig(BaseSequenceValueOpConfig):
    """Configuration class for the :code:`contains` operation."""

    """The :code:`contains` operation."""


class SequenceContains(
    BaseSequenceValueOp[
        SequenceContainsConfig,
        SequenceValueOpInputRefs,
        SequenceContainsOutputRefs,
    ]
):
    """Sequence Contains Data Drocessor.

    This class defines the operation that checks if a value is contained within a sequence.
    """

    _OUTPUT_KEY: ClassVar[str] = "contains"
    op = operator.contains


class SequenceCountOfOutputRefs(OutputRefs):
    """Output references for the :code:`countOf` operation."""

    count: Annotated[FeatureRef, OutputFeature(Value("int64"))]
    """The feature reference to the result of the :code:`countOf` operation."""


class SequenceCountOfConfig(BaseSequenceValueOpConfig):
    """Configuration class for the :code:`countOf operation."""


class SequenceCountOf(
    BaseSequenceValueOp[
        SequenceCountOfConfig,
        SequenceValueOpInputRefs,
        SequenceCountOfOutputRefs,
    ]
):
    """:code:`countOf` Data Processor.

    This class defines the operation that counts occurrences of a value within a sequence.
    """

    _OUTPUT_KEY: ClassVar[str] = "count"
    op = operator.countOf


class SequenceIndexOfOutputRefs(OutputRefs):
    """Output references for the :code:`indexOf` operation."""

    index: Annotated[FeatureRef, OutputFeature(Value("int64"))]
    """The feature reference to the result of the :code:`indexOf` operation."""


class SequenceIndexOfConfig(BaseSequenceValueOpConfig):
    """Configuration class for the :code:`indexOf` operation."""


class SequenceIndexOf(
    BaseSequenceValueOp[
        SequenceIndexOfConfig,
        SequenceValueOpInputRefs,
        SequenceIndexOfOutputRefs,
    ]
):
    """:code:`indexOf` Data Processor.

    This class defines the operation that finds the index of a value within a sequence.
    """

    _OUTPUT_KEY: ClassVar[str] = "index"
    op = operator.indexOf
